Category
CodeWebWeaver/bookstore pull request #10
Opened 2023-09-12 15:25 UTC by CodeWebWeaver

2023-09-12 20:48 UTC, JeniaSan commented on src/main/java/com/parkhomovsky/bookstore/dto/category/CategoryRequestDto.java
> +    private String description;
Read about difference between @Size and @Length and choose the best option

2023-09-12 20:51 UTC, JeniaSan approved these changes
Good job! I left some comments

2023-09-12 20:51 UTC, JeniaSan commented on src/main/java/com/parkhomovsky/bookstore/mapper/BookMapper.java
> +    }
what does this method do?

2023-09-13 13:52 UTC, andrii-hoienko requested changes
Nice, but some improvements required

2023-09-13 13:52 UTC, andrii-hoienko commented on src/main/java/com/parkhomovsky/bookstore/controller/CategoryController.java
> +                               @Valid @RequestBody CategoryRequestDto categoryRequestDto) {
Please be consistent and choose which order is better valid first or requestBody

2023-09-13 13:52 UTC, andrii-hoienko commented on src/main/java/com/parkhomovsky/bookstore/model/Book.java
> +import jakarta.persistence.*;
Try to avoid using asterisk in import

2023-09-13 13:52 UTC, andrii-hoienko commented on src/main/java/com/parkhomovsky/bookstore/model/Book.java
> +    private boolean isDeleted = false;
It is false by default

2023-09-13 13:52 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/03=create-users-table.yaml
> +                    nullable: false
Please add emptyLine in the end of file

2023-09-13 13:52 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/04-create-roles-table.yaml
> +                    unique: true
Please add emptyLine in the end of file

2023-09-13 13:52 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/05-create-users-roles-table.yaml
> +                    nullable: false
Please add emptyLine in the end of file

2023-09-13 13:52 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/06-test-insert-into-roles-table.yaml
> +                  value: ROLE_USER
Please add emptyLine in the end of file

2023-09-13 13:52 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/07-test-insert-in-users-table.yaml
> +                  valueNumeric: 2
Please add emptyLine in the end of file

2023-09-13 13:52 UTC, andrii-hoienko commented on src/main/java/com/parkhomovsky/bookstore/controller/CategoryController.java
> +    public List<CategoryDto> getAllCategories() {
Please implement pagination and sorting

2023-09-14 05:42 UTC, CodeWebWeaver commented on src/main/java/com/parkhomovsky/bookstore/mapper/BookMapper.java
> +    }
IDK

2023-09-14 15:48 UTC, vovasalyha approved these changes
Approving, but please resolve merge conflicts

2023-09-16 10:39 UTC, merged