Shopcart and CartItems models logic implemented v9.0
CodeWebWeaver/bookstore pull request #11
Opened 2023-09-16 10:40 UTC by CodeWebWeaver

2023-09-19 12:41 UTC, andrii-hoienko requested changes
Nice, but significant improvements required

2023-09-19 12:41 UTC, andrii-hoienko commented on src/main/java/com/parkhomovsky/bookstore/exception/GlobalExceptionHandler.java
> +        errorResponse.put(TIMESTAMP, LocalDateTime.now());
It is better to create object something like ErrorResponse/ErrorResponseDto, instead of using map

2023-09-19 12:41 UTC, andrii-hoienko commented on src/main/java/com/parkhomovsky/bookstore/exception/GlobalExceptionHandler.java
> +        errorMessageBody.put("status", HttpStatus.FORBIDDEN);
Are you sure that HttpStatus.FORBIDDEN is the best option in case of InvalidRequestParametersException?

2023-09-19 12:41 UTC, andrii-hoienko commented on src/main/java/com/parkhomovsky/bookstore/exception/GlobalExceptionHandler.java
> +        String errorMessage = "An error occurred while proceeding request data.";
code duplication

2023-09-19 12:41 UTC, andrii-hoienko commented on src/main/java/com/parkhomovsky/bookstore/model/CartItem.java
> +    @ManyToOne
Please make Eager relations Lazy

2023-09-19 12:41 UTC, andrii-hoienko commented on src/main/java/com/parkhomovsky/bookstore/repository/item/CartItemRepository.java
> +    List<CartItem> findByShoppingCartId(Long shoppingCartId);
```suggestion
    List<CartItem> findAllByShoppingCartId(Long shoppingCartId);
```

2023-09-19 12:41 UTC, andrii-hoienko commented on src/main/java/com/parkhomovsky/bookstore/service/implementation/CartItemServiceImpl.java
> +        return bookById.get();
Is it possible to use orElseThrow?

2023-09-19 12:41 UTC, andrii-hoienko commented on src/main/java/com/parkhomovsky/bookstore/service/implementation/CartItemServiceImpl.java
> +        throw new EntityNotFoundException("No item found with provided id");
Please add details to error message

2023-09-19 12:41 UTC, andrii-hoienko commented on src/main/java/com/parkhomovsky/bookstore/service/implementation/CartItemServiceImpl.java
> +        if (possibleCartItem.isPresent()) {
Please move logic of quantity determination to separate method

2023-09-19 12:41 UTC, andrii-hoienko commented on src/main/java/com/parkhomovsky/bookstore/service/implementation/CartItemServiceImpl.java
> +    public CartItemDto create(CreateCartItemRequestDto cartItemDto)
Service methods should not throw UserNotAuthenticatedException. You should configure your app in a way where it is not possible for non Authenticated user to reach service layer

2023-09-19 12:41 UTC, andrii-hoienko commented on src/main/java/com/parkhomovsky/bookstore/service/implementation/CartItemServiceImpl.java
> +            throws UserNotAuthenticatedException, InvalidRequestParametersException {
InvalidRequestParametersException  should not be thrown by service as well. Please make exception handling on dto level

2023-09-19 12:41 UTC, andrii-hoienko commented on src/main/java/com/parkhomovsky/bookstore/service/implementation/CartItemServiceImpl.java
> +        if (possibleCartItem.isPresent()) {
Code duplication

2023-09-19 12:41 UTC, andrii-hoienko commented on src/main/java/com/parkhomovsky/bookstore/service/implementation/CartItemServiceImpl.java
> +            Book bookFromId = getBookFromId(requestCartItem.getBook().getId());
It is possible to move logic of working with book in bookService?

2023-09-19 12:41 UTC, andrii-hoienko commented on src/main/java/com/parkhomovsky/bookstore/service/implementation/CartItemServiceImpl.java
> +public class CartItemServiceImpl implements CartItemService {
Please review this class again and repeat SOLID principles, especially Single Responsibility

2023-09-19 12:41 UTC, andrii-hoienko commented on src/main/java/com/parkhomovsky/bookstore/service/implementation/ShoppingCartServiceImpl.java
> +        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
This logic should be defined in user service

2023-09-19 12:41 UTC, andrii-hoienko commented on src/main/java/com/parkhomovsky/bookstore/service/implementation/ShoppingCartServiceImpl.java
> +    public ShoppingCartDto getUserShoppingCart()
from the method name, this method should only return shopping cart, but does also some population of shopping cart

2023-09-19 12:41 UTC, andrii-hoienko commented on src/main/java/com/parkhomovsky/bookstore/service/implementation/ShoppingCartServiceImpl.java
> +        ShoppingCart shoppingCart = findOrCreateShoppingCartForUser(username);
It is possible to get shopping cart from db with already populated items?

2023-09-19 12:41 UTC, andrii-hoienko commented on src/main/java/com/parkhomovsky/bookstore/service/implementation/ShoppingCartServiceImpl.java
> +        String username = getUsernameFromAuthentication();
Is it possible to get user itself instead of receiving username and then make several more requests in underlying methods to get user

2023-09-19 12:41 UTC, andrii-hoienko commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/11-create-carts-items-table.yaml
Please add an empty line in the end of this file

2023-09-26 12:09 UTC, Vasul-Pankiv approved these changes

2023-09-28 08:51 UTC, merged