implemented data validation, added GlobalExceptionHandler v4.0
CodeWebWeaver/bookstore pull request #5
Opened 2023-09-06 13:35 UTC by Skarbey

2023-09-06 15:08 UTC, Dimagaa requested changes
Well prepared! You can improve it

2023-09-06 15:08 UTC, Dimagaa commented on src/main/java/com/parkhomovsky/bookstore/dto/CreateBookRequestDto.java
> +    @Pattern(regexp = "\\d{13}", message = "ISBN must be 13 digits")
Pretty Good! However, there is @ISBN constraint for this

2023-09-06 15:08 UTC, Dimagaa commented on src/main/java/com/parkhomovsky/bookstore/dto/CreateBookRequestDto.java
> +    @Size(max = 255, message = "Cover image URL must be less than or equal to 255 characters")
Here you can use @Url constraint instead @Size

2023-09-06 15:08 UTC, Dimagaa commented on src/main/java/com/parkhomovsky/bookstore/exception/GlobalExceptionHandler.java
> +
Feel free to add some custom logic  =)

2023-09-08 16:00 UTC, vovasalyha approved these changes
GJ

2023-09-08 16:00 UTC, vovasalyha commented on pom.xml
> +            <groupId>org.hibernate.validator</groupId>
In Spring Boot projects, it's usually better to opt for starters rather than individual dependencies (look for spring-boot-starter-validation)

2023-09-12 14:51 UTC, closed without merging