pagination and v5.0
CodeWebWeaver/bookstore pull request #6
Opened 2023-09-07 17:26 UTC by Skarbey

2023-09-07 18:24 UTC, JeniaSan commented on src/main/java/com/parkhomovsky/bookstore/controller/BookController.java
> +    @Operation(summary = "Get book by id", description = "Try to find book with provided id")
As for me, "Try to find book with provided id" sounds strange. "Find" logic on repository layer, on service and controller layer only "get". And "try" also looks not ok.

2023-09-07 18:28 UTC, JeniaSan commented on src/main/java/com/parkhomovsky/bookstore/controller/BookController.java
> +            "List books on page using parameters")
Parameters? I know what you mean, but I think it's better to remove it

2023-09-07 18:29 UTC, JeniaSan commented on src/main/java/com/parkhomovsky/bookstore/controller/BookController.java
> +    @Operation(summary = "Delete book by id", description = "Delete book from database")
Wrong description, you don't delete book from database (remember about soft delete)

2023-09-07 18:33 UTC, JeniaSan requested changes
Good solution, let's improve it!

2023-09-08 06:38 UTC, JeniaSan approved these changes
Good job!

2023-09-08 17:29 UTC, Vasul-Pankiv approved these changes

2023-09-12 14:47 UTC, merged